# Generated by Django 5.1.7 on 2025-06-02 11:26

from django.db import migrations, models


def preconvert_expires_in_for_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    spotify_token_table = apps.get_model("spotify", "SpotifyToken")._meta.db_table
    schema_editor.execute(
        f"""
        ALTER TABLE "{spotify_token_table}"
        ALTER COLUMN "expires_in"
        TYPE timestamp with time zone
        USING (NOW() + ("expires_in" * INTERVAL '1 second'))
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=preconvert_expires_in_for_postgres,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="expires_in",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
