# Generated by Django 5.1.7 on 2025-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_song",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
