# Generated by Django 5.1.7 on 2026-05-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_room_current_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="multi_device_sync",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=50)),
                ("spotify_linked", models.BooleanField(default=False)),
                (
                    "selected_device_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "selected_device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_sync_enabled", models.BooleanField(default=True)),
                ("last_sync_error", models.TextField(blank=True, default="")),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="api.room",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "session_id"),
                        name="unique_room_session_participant",
                    )
                ],
            },
        ),
    ]
